# Generated by Django 5.2.7 on 2025-11-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='nohp',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
