# Generated by Django 5.2.7 on 2026-01-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_alamat_mahasiswa_jurusan_mahasiswa_nohp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('homebase', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'verbose_name': 'Mahasiswa', 'verbose_name_plural': 'Mahasiswas'},
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='alamat',
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nama',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='npm',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mk', models.CharField(max_length=100)),
                ('kode_mk', models.CharField(max_length=10, unique=True)),
                ('sks', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('mhs_mk', models.IntegerField()),
                ('dosen_mk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.dosen')),
            ],
        ),
    ]
